name: Backend CI/CD

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

  pull_request:
    branches:
      - main
      - staging
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache-dependency-path: backend/yarn.lock

      - name: Corepack Enable
        run: |
          corepack enable
          corepack install

      - name: Check versions
        run: |
          node -v
          corepack --version
          yarn -v

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: "1"
        run: yarn install --immutable

      - name: Audit dependencies
        run: yarn npm audit --all --recursive --severity high

      - name: Generate Prisma
        run: yarn prisma generate

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Trigger Render Staging Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
        run: curl --fail --silent --show-error --request POST "${{ secrets.STG_RENDER_DEPLOY_HOOK }}"

      - name: Trigger Render Production Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl --fail --silent --show-error --request POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
