name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24

      - name: Corepack Enable
        run: |
          corepack enable
          corepack install

      - name: Check versions
        run: |
          node -v
          corepack --version
          yarn -v

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: "1"
        run: yarn install --immutable

      - name: Audit dependencies
        run: yarn npm audit --all --recursive --severity high

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build
        run: yarn build

      - name: Netlify Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --build --prod
          echo "✅ Netlify deploy triggered successfully."
