name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache-dependency-path: backend/yarn.lock
      
      - name: Corepack Enable
        run: |
          corepack enable
          corepack install

      - name: Check versions
        run: |
          node -v
          corepack --version
          yarn -v

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Generate Prisma
        run: yarn prisma generate

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Trigger Render Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

  frontend:
    name: Frontend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Trigger Netlify Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl --fail --show-error --silent --write-out "\nHTTP Status: %{http_code}\n" \
          -X POST "${{ secrets.NETLIFY_DEPLOY_HOOK }}"